# Generated by Django 5.0 on 2023-12-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
